<!-- content block -->
<div class="article_box">
	<h1 style="margin: 0px; padding: 0px; font-size: 19px; text-align: center; font-family: Georgia, serif; ">
		ASHLEYASHOFF.com Privacy Policy (USA July 2007)</h1>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		Please read the present Terms and Conditions carefully.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		The ASHLEY ASHOF.com website is operated by ASHLEY ASHOFF and Company. ASHLEY ASHOFF and Company hosts and operates the ASHLEYASHOFF.com website, including processing and storing all of the data collected on or through the website. ASHLEY ASHOFF and Company has created this privacy policy ("Privacy Policy") in order to communicate ASHLEY ASHOFF and Company?s policies and practices relating to the collection, use and disclosure of information about you obtained on the ASHLEYASHOFF.com website.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		Please read this Privacy Policy carefully. ASHLEY ASHOFF and Company may change or update this Privacy Policy periodically.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		If you decide to use the ASHLEYASHOFF.com website, or by agreeing to the ASHLEYASHOFF.com Terms and Conditions, you consent to the collection, the use and the disclosure of your information, including personal and financial information, by ASHLEY ASHOFF and Company on the terms described in this Privacy Policy. If you do not agree with the terms of this Privacy Policy, or any modifications thereto, please exit the ASHLEYASHOFF.com website now and do not purchase any of the ASHLEY ASHOFF products offered for sale on the website.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		What information is collected on ASHLEYASHOFF.com?</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		You may use the ASHLEYASHOFF.com website without providing any personal information to ASHLEY ASHOFF and Company. You will however, need to provide certain information, including your name, address, telephone number and e-mail address, as well as certain financial information (such as your charge or credit card number) if you choose to purchase products offered on the ASHLEYASHOFF.com website for the purposes of paying for the products you ordered and processing your order. Any information you provide on the ASHLEYASHOFF.com website may be processed in the U.S. or in France and will be stored on ASHLEY ASHOFF and Company server in the U.S.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		You may choose to allow ASHLEY ASHOFF and Company to store this information in the ASHLEY ASHOFF customer database without taking any further step. You may also request by sending an e-mail to ASHLEY ASHOFF and Company to delete your personal information at any time as soon as your order has been processed and delivered.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		Receiving Information</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		ASHLEY ASHOFF and Company also provides you with the opportunity to receive information from ASHLEY ASHOFF and Company, which may be of interest to you, including information relating to new products offered on the ASHLEYASHOFF.com website. If you do not want to receive such information by e-mail, you may opt-out of further communications at any time by contacting our customer service department by e-mail at&nbsp;<a href="mailto:customerservice@ashleyashoff.com" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); ">customerservice@ashleyashoff.com</a>.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		What use is made of the information you provide on ASHLEYASHOFF.com?</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		ASHLEY ASHOFF and Company may disclose the information you provide on the ASHLEYASHOFF.com website to offices in both California and France, in order to process your order and deliver it to you.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		ASHLEY ASHOFF and Company may also disclose the information you provide on the ASHLEYASHOFF.com website to offices in California and France, in order that such affiliates may contact you with respect to information about such corporate affiliates, including products and services of such corporate affiliates that may be of interest to you. If you do not want to receive such information by email, you may opt out as set forth above in the section entitled "Receiving Information"</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		ASHLEY ASHOFF and Company may also disclose the information you provide to her on the ASHLEYASHOFF.com website to third parties who provide services on or to the ASHLEYASHOFF.com website. To verify your information, authenticate payments and process orders, ASHLEY ASHOFF and Company may disclose certain financial and other information you provide to ASHLEY ASHOFF and Company to third parties that provide credit reporting, payment or order fulfillment services.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		ASHLEY ASHOFF and Company may disclose your information if we believe in good faith that such disclosure is necessary to comply with applicable law, a subpoena or other legal process. For example, ASHLEY ASHOFF and Company may disclose such information as is necessary to identify, contact or bring legal action against a person or entity who may be violating the ASHLEYASHOFF.com Terms and Conditions, or who may be causing injury to, or interfering with, other users of the ASHLEYASHOFF.com website. In the event that ASHLEY ASHOFF and Company, or all or part of its or their assets, are acquired by a third party, the ASHLEYASHOFF.com customer list may be included in the transferred assets.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		Please be aware that ASHLEY ASHOFF and Company does not control the policies or practices of third parties to which ASHLEY ASHOFF and Company discloses information about users of the ASHLEYASHOFF.com website and that any use or disclosure of such information by third parties is not governed by this Privacy Policy.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		[For California Residents], What are your rights under California Civil Code Sections 1798.83-1798.84?</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		California Civil Code sections 1798.83-1798.84 give California residents the right to ask us for a notice describing what categories of personal customer information we share with third parties or corporate affiliates for their direct marketing purposes. That notice will identify the categories of information shared and will include a list of the third parties and affiliates with which it was shared, along with their names and address. If you are a California resident and would like a copy of this notice, please submit a written request to:&nbsp;<a href="mailto:customerservice@ashleyashoff.com" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); ">customerservice@ashleyashoff.com</a>.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		Cookies</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		ASHLEY ASHOFF and Company reserves the right to use cookies and similar devices on the ASHLEYASHOFF.com website to facilitate site-navigation and to customize the information that appears on the ASHLEYASHOFF.com website. ASHLEY ASHOFF and Company also reserves the right to use cookies and similar devices to collect non-personal information about users of the ASHLEYASHOFF.com website, such as a user's IP address, the type of web browser and operating system being used and/or the pages of the website a user visits. ASHLEY ASHOFF and Company collects this information in order to monitor usage of the ASHLEYASHOFF.com website and to improve aspects of the website.</p>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		Most browsers accept cookies automatically, but can also be configured not to do so or to indicate when a cookie is being sent. We recommend that you do not disable your browser from accepting cookies, as it will prevent you from moving freely from page to page and from taking advantage of all of the features of the ASHLEYASHOFF.com website.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		Links</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		The ASHLEYASHOFF.com website may contain links to other third party websites. ASHLEY ASHOFF and Company has no control over the content, policies or actions of these websites. The use of any information you may provide to third parties on other websites, or which such parties may otherwise collect on other websites, is not governed by this Privacy Policy. You should carefully review the privacy policies of any third party websites and contact the operators of those websites if you have any questions about their use of your information. ASHLEY ASHOFF and Company cannot be responsible for any third party, or its affiliates or agents, failing to use your personal information in accordance with such third party's privacy policy, or any contractual or other legal obligations to which such third party, its affiliates or agents, may be subject.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		Security</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		ASHLEY ASHOFF and Company has implemented security measures to protect the personal information you provide against unauthorized access and use. All financial information you provide on the ASHLEYASHOFF.com website is stored on a secure site operated by ASHLEY ASHOFF and Company?s financial institution. Transactions conducted on the ASHLEYASHOFF.com website are protected by an SSL encrypting system. Please be aware, however, that no data transmission over the Internet is 100% secure and any information disclosed online can potentially be collected and used by persons other than the intended recipient.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		Changes and Updates to Privacy Policy</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		By using the ASHLEYASHOFF.com website, you consent to the collection, use and disclosure of your information as described in this Privacy Policy. This Privacy Policy reflects ASHLEY ASHOFF and Company's current business practices, and is subject to change and update. In the event of any such change or update, a revised policy will be posted on line on the ASHLEYASHOF.com website, with the last date of update noted on the bottom of the page. Please check the ASHLEYASHOFF.com website periodically to remain informed of any changes or updates to ASHLEY ASHOFF and Company?s privacy policies and practices. If you allow ASHLEY ASHOFF and Company to retain the personal information you provide on the ASHLEYASHOFF.com website in its customer database and ASHLEY ASHOFF and Company intends to disclose that information to third parties or affiliated companies in a manner that is not already outlined in this Privacy Policy, ASHLEY ASHOFF and Company will notify you by e-mail and provide you with an opportunity to opt out of any further use or disclosure of your personal information.</p>
	<h3 style="margin: 1em 0px 0px; padding: 0px; font-size: 15px; font-family: Georgia, serif; ">
		Changes and Access to Your Personal Information</h3>
	<p style="margin: 1em 0px 0px; padding: 0px; font-family: Georgia, serif; font-size: 13px; ">
		You may ask ASHLEY ASHOFF and Company to correct, update or delete information you have provided to ASHLEY ASHOFF and Company and of which you allowed to registration in the ASHLEY ASHOFF customer database by contacting our customer service (see "Contact us"). If applicable, you should be sure to provide ASHLEY ASHOFF and Company with any updates and changes to your information, including any changes to your postal or e-mail address to ensure that your orders are shipped to the correct address and that we can contact you about your order if necessary. ASHLEY ASHOFF and Company may also retain, for archival purposes, copies of communications with users of the ASHLEYASHOFF.com website and any response to questions or comments sent to users by ASHLEY ASHOFF and Company.</p>
</div>
<!-- tail block --><!-- ARTICLE: end -->